name: google java format

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  pull-requests: read
  statuses: write

jobs:
  google-java-format:
    name: google java format
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: google java format
        uses: super-linter/super-linter@v6.4.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: DEBUG
          # only lint new and modified files
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_GOOGLE_JAVA_FORMAT: true
