name: maven dependency submission

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  dependency-submission-maven:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java-version: "17"
            java-distribution: "temurin"
  
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
  
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4
